// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use wityh your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5T-_r2VXa7wg-kf4lT1iIg-mzadQ3qXQ',
    appId: '1:104357651178:web:d0571187dec51001ad6d93',
    messagingSenderId: '104357651178',
    projectId: 'reddit-6b029',
    authDomain: 'reddit-6b029.firebaseapp.com',
    storageBucket: 'reddit-6b029.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUKDG5dkdBwe3snvbVkCnvjlke9tqtJHc',
    appId: '1:104357651178:android:4c2408393502f920ad6d93',
    messagingSenderId: '104357651178',
    projectId: 'reddit-6b029',
    storageBucket: 'reddit-6b029.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ydiqxhDirKQM2TsmvoItAJTReUtbrxc',
    appId: '1:104357651178:ios:d036b25947f8bf04ad6d93',
    messagingSenderId: '104357651178',
    projectId: 'reddit-6b029',
    storageBucket: 'reddit-6b029.appspot.com',
    iosClientId: '104357651178-e8oc8c2eent1f7gsvlvf5amclmjf4di1.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ydiqxhDirKQM2TsmvoItAJTReUtbrxc',
    appId: '1:104357651178:ios:d036b25947f8bf04ad6d93',
    messagingSenderId: '104357651178',
    projectId: 'reddit-6b029',
    storageBucket: 'reddit-6b029.appspot.com',
    iosClientId: '104357651178-e8oc8c2eent1f7gsvlvf5amclmjf4di1.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
